#!/usr/bin/env node
/**
 * JP Apex Lab — Interactive Setup Script
 *
 * Walks through Tier 1 (required) and prompts for optional integrations.
 * Creates a local .env file and adds GitHub Actions secrets via `gh` CLI.
 *
 * Usage:  node scripts/setup.mjs
 * Requires: gh CLI authenticated  →  gh auth login
 */

import { createInterface } from 'readline';
import { execSync, spawnSync } from 'child_process';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_PATH = join(ROOT, '.env');

// ── Helpers ──────────────────────────────────────────────────────────────────

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));
const askOptional = (q) => ask(`${q} (press Enter to skip) `);

function header(text) {
  const line = '─'.repeat(60);
  console.log(`\n${line}\n  ${text}\n${line}`);
}

function ok(msg)   { console.log(`  ✓  ${msg}`); }
function info(msg) { console.log(`  →  ${msg}`); }
function warn(msg) { console.log(`  ⚠  ${msg}`); }
function die(msg)  { console.error(`\n  ✗  ${msg}\n`); process.exit(1); }

function ghAvailable() {
  const r = spawnSync('gh', ['auth', 'status'], { stdio: 'pipe' });
  return r.status === 0;
}

function setSecret(repo, name, value) {
  if (!value || !value.trim()) return;
  const r = spawnSync('gh', ['secret', 'set', name, '--body', value.trim(), '--repo', repo],
    { stdio: 'pipe' });
  if (r.status !== 0) {
    warn(`Could not set secret ${name}: ${r.stderr?.toString().trim()}`);
  } else {
    ok(`GitHub secret set: ${name}`);
  }
}

function writeEnvLine(key, value, envLines) {
  if (!value || !value.trim()) return;
  envLines.push(`${key}=${value.trim()}`);
  ok(`Local .env: ${key}`);
}

// ── Main ─────────────────────────────────────────────────────────────────────

console.log('\n╔══════════════════════════════════════════════════════════╗');
console.log('║         JP Apex Lab — Interactive Setup                  ║');
console.log('╚══════════════════════════════════════════════════════════╝');
console.log('\nThis script will:');
console.log('  1. Create a local .env file');
console.log('  2. Add GitHub Actions secrets to your fork');
console.log('\nRead SETUP.md first for context on what each step does.\n');

// ── Check gh CLI ─────────────────────────────────────────────────────────────

if (!ghAvailable()) {
  warn('GitHub CLI (gh) is not authenticated.');
  warn('Run: gh auth login');
  warn('Continuing — secrets will NOT be added automatically.');
  warn('You can add them manually via SETUP.md "Manual secrets reference".\n');
}

// ── GitHub repo ──────────────────────────────────────────────────────────────

header('Step 1 of 5 — Your GitHub info');
info('Your forked repo should be at github.com/YOUR-USERNAME/apex-lab\n');

const ghUser = (await ask('  Your GitHub username: ')).trim();
if (!ghUser) die('GitHub username is required.');
const repo = `${ghUser}/apex-lab`;
ok(`Repo: ${repo}`);

// ── Env lines accumulator ────────────────────────────────────────────────────

const envLines = [
  `# JP Apex Lab — local dev environment`,
  `# Generated by scripts/setup.mjs`,
  `# DO NOT commit this file to git`,
  '',
];

// ── Tier 1 — Google ──────────────────────────────────────────────────────────

header('Step 2 of 5 — Google OAuth (required)');
info('From Google Cloud Console → APIs & Services → Credentials');
info('See SETUP.md step 1-C for how to create this.\n');

const googleClientId = (await ask('  VITE_GOOGLE_CLIENT_ID: ')).trim();
if (!googleClientId || !googleClientId.includes('.apps.googleusercontent.com')) {
  warn('That doesn\'t look like a Google Client ID — continuing anyway.');
}

writeEnvLine('VITE_GOOGLE_CLIENT_ID', googleClientId, envLines);
setSecret(repo, 'VITE_GOOGLE_CLIENT_ID', googleClientId);

// ── Tier 2 — Health provider ─────────────────────────────────────────────────

header('Step 3 of 5 — Health data (optional)');
console.log('  Options:');
console.log('    O  → Oura Ring (simplest — just a token, no Cloudflare needed)');
console.log('    W  → WHOOP    (requires Cloudflare Worker — see SETUP.md Tier 2-B)');
console.log('    S  → Strava   (requires Cloudflare Worker — see SETUP.md Tier 2-C)');
console.log('    N  → None / skip\n');

const healthChoice = (await ask('  Your choice [O/W/S/N]: ')).trim().toUpperCase();
envLines.push('');

if (healthChoice === 'O') {
  info('Oura: generate a token at https://cloud.ouraring.com/personal-access-tokens\n');
  const ouraToken = (await ask('  VITE_OURA_PERSONAL_TOKEN: ')).trim();
  writeEnvLine('VITE_OURA_PERSONAL_TOKEN', ouraToken, envLines);
  setSecret(repo, 'VITE_OURA_PERSONAL_TOKEN', ouraToken);
  // Also set OURA_TOKEN for health cache workflow
  setSecret(repo, 'OURA_TOKEN', ouraToken);
  info('\nUpdate src/config.ts:  healthProvider: \'oura\'');
  info('Then: git add src/config.ts && git commit -m "config: enable Oura" && git push');

} else if (healthChoice === 'W') {
  info('WHOOP: you need a Cloudflare Worker deployed first — see SETUP.md Tier 2-B.');
  info('Then come back and run this script again, or add the secrets manually.\n');
  const whoopId     = (await ask('  VITE_WHOOP_CLIENT_ID: ')).trim();
  const whoopSecret = (await ask('  VITE_WHOOP_CLIENT_SECRET: ')).trim();
  const whoopWorker = (await ask('  Cloudflare Worker URL (e.g. https://apex-worker.xxx.workers.dev): ')).trim();
  writeEnvLine('VITE_WHOOP_CLIENT_ID', whoopId, envLines);
  writeEnvLine('VITE_WHOOP_CLIENT_SECRET', whoopSecret, envLines);
  setSecret(repo, 'VITE_WHOOP_CLIENT_ID', whoopId);
  setSecret(repo, 'VITE_WHOOP_CLIENT_SECRET', whoopSecret);
  if (whoopWorker) setSecret(repo, 'WHOOP_WORKER_URL', whoopWorker);
  info('\nUpdate src/config.ts:');
  info("  healthProvider: 'whoop',");
  info(`  whoopWorkerUrl: '${whoopWorker || 'YOUR-WORKER-URL'}',`);

} else if (healthChoice === 'S') {
  info('Strava: you need a Cloudflare Worker deployed first — see SETUP.md Tier 2-C.');
  info('Then come back and run this script again, or add the secrets manually.\n');
  const stravaId     = (await ask('  VITE_STRAVA_CLIENT_ID: ')).trim();
  const stravaSecret = (await ask('  VITE_STRAVA_CLIENT_SECRET: ')).trim();
  writeEnvLine('VITE_STRAVA_CLIENT_ID', stravaId, envLines);
  writeEnvLine('VITE_STRAVA_CLIENT_SECRET', stravaSecret, envLines);
  setSecret(repo, 'VITE_STRAVA_CLIENT_ID', stravaId);
  setSecret(repo, 'VITE_STRAVA_CLIENT_SECRET', stravaSecret);
  info('\nUpdate src/config.ts:');
  info("  healthProvider: 'strava',");
  info("  stravaWorkerUrl: 'YOUR-CLOUDFLARE-WORKER-URL',");
  info('Then register the Strava webhook — see SETUP.md step 2-C-4.');

} else {
  info('Skipping health integration. Set healthProvider: null in src/config.ts (already the default).');
}

// ── Tier 3 — AI Coaching ─────────────────────────────────────────────────────

header('Step 4 of 5 — AI Coaching (optional)');
console.log('  Option A: each user enters their own Anthropic key in Settings — no setup needed.');
console.log('  Option B: deploy a shared Vercel proxy so users don\'t need their own key.\n');

const aiChoice = (await ask('  Set up Vercel proxy now? [y/N]: ')).trim().toLowerCase();
envLines.push('');

if (aiChoice === 'y') {
  info('Deploy to Vercel first: https://vercel.com → New Project → import apex-lab');
  info('Add ANTHROPIC_API_KEY in Vercel → Settings → Environment Variables.');
  info('Then come back with your Vercel deployment URL.\n');
  const vercelUrl = (await ask('  Vercel deployment URL (e.g. https://apex-lab-xyz.vercel.app): ')).trim();
  if (vercelUrl) {
    writeEnvLine('VITE_COACHING_WORKER_URL', vercelUrl, envLines);
    setSecret(repo, 'VITE_COACHING_WORKER_URL', vercelUrl);
    info('\nAfter setting ANTHROPIC_API_KEY in Vercel, trigger a rebuild:');
    info('  git commit --allow-empty -m "chore: add coaching proxy" && git push');
  }
} else {
  info('Skipped. Users will provide their own Anthropic key in Settings → AI Coaching.');
}

// ── Tier 4 — Push Notifications ──────────────────────────────────────────────

header('Step 5 of 5 — Push Notifications (optional)');
info('Requires a Cloudflare Worker from Tier 2 (WHOOP or Strava).\n');

const pushChoice = (await ask('  Generate VAPID keys and configure push notifications? [y/N]: ')).trim().toLowerCase();
envLines.push('');

if (pushChoice === 'y') {
  info('Generating VAPID keys...\n');
  try {
    // Run the keygen script and capture output
    const result = spawnSync('node', ['scripts/gen-vapid-keys.mjs'], {
      cwd: ROOT, stdio: 'pipe', encoding: 'utf8',
    });
    const output = result.stdout || '';
    const pubMatch = output.match(/VITE_VAPID_PUBLIC_KEY=(\S+)/);
    const privMatch = output.match(/VAPID_PRIVATE_KEY[^\n]*\n(\S+)/);
    const pubKey  = pubMatch?.[1];
    const privKey = privMatch?.[1];

    if (pubKey) {
      writeEnvLine('VITE_VAPID_PUBLIC_KEY', pubKey, envLines);
      setSecret(repo, 'VITE_VAPID_PUBLIC_KEY', pubKey);
      ok('VAPID public key generated and saved.');
    }
    if (privKey) {
      console.log('\n  ┌─────────────────────────────────────────────────────┐');
      console.log('  │  VAPID PRIVATE KEY — add to Cloudflare Worker       │');
      console.log('  │  Worker → Settings → Variables → VAPID_PRIVATE_KEY  │');
      console.log('  └─────────────────────────────────────────────────────┘');
      console.log(`\n  ${privKey}\n`);
      info('Copy the private key above and add it to your Cloudflare Worker env vars.');
    }
  } catch (e) {
    warn('Could not generate VAPID keys automatically. Run manually: node scripts/gen-vapid-keys.mjs');
  }
} else {
  info('Skipped. Push notifications can be enabled later — see SETUP.md Tier 4.');
}

// ── Write .env ────────────────────────────────────────────────────────────────

header('Writing .env file');

envLines.push('');
const envContent = envLines.join('\n') + '\n';
writeFileSync(ENV_PATH, envContent, 'utf8');
ok(`.env written to ${ENV_PATH}`);
info('.env is in .gitignore — it will NOT be committed to git.');

// ── Final instructions ────────────────────────────────────────────────────────

header('Setup complete — next steps');

console.log('  1. Update src/config.ts with your Drive folder ID and any health config');
console.log('     (see SETUP.md for the exact lines to change)\n');
console.log('  2. Push to deploy:');
console.log('     git add src/config.ts && git commit -m "config: personal setup" && git push\n');
console.log(`  3. Watch the build: https://github.com/${repo}/actions\n`);
console.log(`  4. Your app will be live at:`);
console.log(`     https://${ghUser}.github.io/apex-lab/\n`);
console.log('  Read SETUP.md for full documentation on each integration.\n');

rl.close();
