#!/usr/bin/env node
/**
 * Apex Lab: Interactive Setup Script
 *
 * Walks through Tier 1 (required) and prompts for optional AI coaching.
 * Creates a local .env file and adds GitHub Actions secrets via `gh` CLI.
 *
 * Usage:  node scripts/setup.mjs
 * Requires: gh CLI authenticated (gh auth login)
 */

import { createInterface } from 'readline';
import { spawnSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_PATH = join(ROOT, '.env');

// Helpers
const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

function header(text) {
  const line = '\u2500'.repeat(60);
  console.log(`\n${line}\n  ${text}\n${line}`);
}

function ok(msg)   { console.log(`  \u2713  ${msg}`); }
function info(msg) { console.log(`  \u2192  ${msg}`); }
function warn(msg) { console.log(`  \u26A0  ${msg}`); }
function die(msg)  { console.error(`\n  \u2717  ${msg}\n`); process.exit(1); }

function ghAvailable() {
  const r = spawnSync('gh', ['auth', 'status'], { stdio: 'pipe' });
  return r.status === 0;
}

function setSecret(repo, name, value) {
  if (!value || !value.trim()) return;
  const r = spawnSync('gh', ['secret', 'set', name, '--body', value.trim(), '--repo', repo],
    { stdio: 'pipe' });
  if (r.status !== 0) {
    warn(`Could not set secret ${name}: ${r.stderr?.toString().trim()}`);
  } else {
    ok(`GitHub secret set: ${name}`);
  }
}

function writeEnvLine(key, value, envLines) {
  if (!value || !value.trim()) return;
  envLines.push(`${key}=${value.trim()}`);
  ok(`Local .env: ${key}`);
}

// Main
console.log('\n\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557');
console.log('\u2551         Apex Lab: Interactive Setup                     \u2551');
console.log('\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D');
console.log('\nThis script will:');
console.log('  1. Create a local .env file');
console.log('  2. Add GitHub Actions secrets to your fork');
console.log('\nRead SETUP.md first for context on what each step does.\n');

// Check gh CLI
if (!ghAvailable()) {
  warn('GitHub CLI (gh) is not authenticated.');
  warn('Run: gh auth login');
  warn('Continuing, secrets will NOT be added automatically.\n');
}

// GitHub repo
header('Step 1 of 3: Your GitHub info');
info('Your forked repo should be at github.com/YOUR-USERNAME/apex-lab\n');

const ghUser = (await ask('  Your GitHub username: ')).trim();
if (!ghUser) die('GitHub username is required.');
const repo = `${ghUser}/apex-lab`;
ok(`Repo: ${repo}`);

// Env lines accumulator
const envLines = [
  `# Apex Lab: local dev environment`,
  `# Generated by scripts/setup.mjs`,
  `# DO NOT commit this file to git`,
  '',
];

// Tier 1: Google
header('Step 2 of 3: Google OAuth (required)');
info('From Google Cloud Console, APIs & Services, Credentials');
info('See SETUP.md step 1-C for how to create this.\n');

const googleClientId = (await ask('  VITE_GOOGLE_CLIENT_ID: ')).trim();
if (!googleClientId || !googleClientId.includes('.apps.googleusercontent.com')) {
  warn('That doesn\'t look like a Google Client ID, continuing anyway.');
}

writeEnvLine('VITE_GOOGLE_CLIENT_ID', googleClientId, envLines);
setSecret(repo, 'VITE_GOOGLE_CLIENT_ID', googleClientId);

// Tier 2: AI Coaching
header('Step 3 of 3: AI Coaching (optional)');
console.log('  Option A: each user enters their own Anthropic key in Settings (no setup needed).');
console.log('  Option B: deploy a shared Vercel proxy so users don\'t need their own key.\n');

const aiChoice = (await ask('  Set up Vercel proxy now? [y/N]: ')).trim().toLowerCase();
envLines.push('');

if (aiChoice === 'y') {
  info('Deploy to Vercel first: https://vercel.com, New Project, import apex-lab');
  info('Add ANTHROPIC_API_KEY in Vercel, Settings, Environment Variables.');
  info('Then come back with your Vercel deployment URL.\n');
  const vercelUrl = (await ask('  Vercel deployment URL (e.g. https://apex-lab-xyz.vercel.app): ')).trim();
  if (vercelUrl) {
    writeEnvLine('VITE_COACHING_WORKER_URL', vercelUrl, envLines);
    setSecret(repo, 'VITE_COACHING_WORKER_URL', vercelUrl);
    info('\nAfter setting ANTHROPIC_API_KEY in Vercel, trigger a rebuild:');
    info('  git commit --allow-empty -m "chore: add coaching proxy" && git push');
  }
} else {
  info('Skipped. Users will provide their own Anthropic key in Settings.');
}

// Write .env
header('Writing .env file');

envLines.push('');
const envContent = envLines.join('\n') + '\n';
writeFileSync(ENV_PATH, envContent, 'utf8');
ok(`.env written to ${ENV_PATH}`);
info('.env is in .gitignore, it will NOT be committed to git.');

// Final instructions
header('Setup complete: next steps');

console.log('  1. Update src/config.ts with your Drive folder ID');
console.log('     (see SETUP.md for the exact lines to change)\n');
console.log('  2. Push to deploy:');
console.log('     git add src/config.ts && git commit -m "config: personal setup" && git push\n');
console.log(`  3. Watch the build: https://github.com/${repo}/actions\n`);
console.log(`  4. Your app will be live at:`);
console.log(`     https://${ghUser}.github.io/apex-lab/\n`);
console.log('  Read SETUP.md for full documentation.\n');

rl.close();
